### ISSUE TITLE
Failing When SYNC_STATICDHCPLEASES: true

### ISSUE THREAD

**Issue by pmontgo33** [mattwebbio/orbital-sync#124]
### What happened?

I'd like to use orbital sync to keep static DHCP lease consistent. When I enable this with SYNC_STATICDHCPLEASES: true, the sync fails.

```
orbital-sync:
    image: mattwebbio/orbital-sync:latest
    container_name: orbital-sync
    environment:
      SYNC_STATICDHCPLEASES: true
      TZ: "America/New_York"
      PRIMARY_HOST_BASE_URL: 'http://192.168.86.101:8080'
      PRIMARY_HOST_PASSWORD: 'removed'
      SECONDARY_HOST_1_BASE_URL: 'http://192.168.86.102:8080'
      SECONDARY_HOST_1_PASSWORD: 'removed'
```

### Version

latest docker container

### Log output

```shell
1/22/2023, 3:43:05 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 3:43:05 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 3:43:05 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 3:43:13 AM: Waiting 30 minutes...
1/22/2023, 3:43:13 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 3:43:13 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 4:13:13 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 4:13:13 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 4:13:13 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 4:13:13 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 4:13:13 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 4:13:13 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 4:13:13 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 4:13:21 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 4:13:21 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 4:13:21 AM: Waiting 30 minutes...
1/22/2023, 4:43:21 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 4:43:21 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 4:43:21 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 4:43:21 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 4:43:21 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 4:43:21 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 4:43:21 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 4:43:27 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 4:43:27 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 4:43:27 AM: Waiting 30 minutes...
1/22/2023, 5:13:27 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 5:13:27 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 5:13:27 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 5:13:27 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 5:13:27 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 5:13:27 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 5:13:27 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 5:13:35 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 5:13:35 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 5:13:35 AM: Waiting 30 minutes...
1/22/2023, 5:43:35 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 5:43:35 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 5:43:35 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 5:43:35 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 5:43:35 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 5:43:35 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 5:43:35 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 5:43:41 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 5:43:41 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 5:43:41 AM: Waiting 30 minutes...
1/22/2023, 6:13:41 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 6:13:41 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 6:13:41 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 6:13:41 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 6:13:41 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 6:13:41 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 6:13:41 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 6:13:47 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 6:13:47 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 6:13:47 AM: Waiting 30 minutes...
1/22/2023, 6:43:47 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 6:43:47 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 6:43:47 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 6:43:47 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 6:43:47 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 6:43:47 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 6:43:47 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 6:43:53 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 6:43:53 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 6:43:53 AM: Waiting 30 minutes...
1/22/2023, 7:13:53 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 7:13:53 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 7:13:53 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 7:13:53 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 7:13:53 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 7:13:53 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 7:13:53 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 7:14:01 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 7:14:01 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 7:14:01 AM: Waiting 30 minutes...
1/22/2023, 7:44:01 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 7:44:01 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 7:44:01 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 7:44:01 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 7:44:01 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 7:44:01 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 7:44:01 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 7:44:09 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 7:44:09 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 7:44:09 AM: Waiting 30 minutes...
1/22/2023, 8:14:09 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 8:14:09 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 8:14:09 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 8:14:09 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 8:14:09 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 8:14:09 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 8:14:09 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 8:14:15 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 8:14:15 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 8:14:15 AM: Waiting 30 minutes...
1/22/2023, 8:44:15 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 8:44:18 AM: ⚠ Failure: An unexpected error was thrown:
- FetchError: request to http://192.168.86.101:8080/admin/index.php?login failed, reason: connect EHOSTUNREACH 192.168.86.101:8080
1/22/2023, 8:44:18 AM: Waiting 30 minutes...
```

**Comment by mattwebbio** [comment]
Would you mind setting `VERBOSE: true` and sharing the output?

**Comment by pmontgo33** [comment]
1/22/2023, 9:52:23 AM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 9:52:23 AM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 9:52:23 AM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 9:52:23 AM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 9:52:23 AM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 9:52:23 AM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 9:52:23 AM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 9:52:31 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 9:52:31 AM: {"host":"http://192.168.86.102:8080","path":"/admin","status":200,"responseBody":"Processed adlist (42 entries)<br>\nProcessed adlist group assignments (42 entries)<br>\nProcessed blacklist (exact) (3 entries)<br>\nProcessed blacklist (regex) (1 entry)<br>\nProcessed client (0 entries)<br>\nProcessed client group assignments (0 entries)<br>\nProcessed local DNS records (2 entries)<br>\nProcessed static DHCP leases (16 entries)<br>\nProcessed black-/whitelist group assignments (279 entries)<br>\nProcessed group (1 entry)<br>\nProcessed whitelist (exact) (274 entries)<br>\nProcessed whitelist (regex) (1 entry)<br>\nOK<br>\n<span data-forcereload></span>"}
1/22/2023, 9:52:31 AM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 9:52:31 AM: Waiting 30 minutes...

**Comment by mattwebbio** [comment]
So I'm _not_ sure why this is only happening for you, but I do have a theory on how to fix it. Could you try this prerelease tag?
```
orbital-sync:
    image: mattwebbio/orbital-sync:1.5.1-0
```

**Comment by pmontgo33** [comment]
Thanks for working on this! Looks like it is still failing. Here is the log when run with the prerelease:

1/22/2023, 2:42:10 PM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 2:42:11 PM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 2:42:11 PM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 2:42:11 PM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 2:42:11 PM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 2:42:11 PM: ⚠ Failure: An unexpected error was thrown:
- FetchError: request to http://192.168.86.102:8080/admin/index.php?login failed, reason: socket hang up
1/22/2023, 2:42:11 PM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 2:42:11 PM: Waiting 30 minutes...

**Comment by mattwebbio** [comment]
There may be two separate issues here. The prerelease should fix the issue shown in your 2nd log output (where it says `Failed to upload backup to ...`), but that latest log output (where it says `FetchError: request to ... failed`) indicates that the secondary host isn't accessible by Orbital Sync (the request to Pi-hole seems to be timing out)

**Comment by pmontgo33** [comment]
I double checked that everything is running ok and restarted the orbit sync container. Here is the error I see now:

1/22/2023, 2:57:31 PM: ➡️ Signing in to http://192.168.86.101:8080/admin...
1/22/2023, 2:57:31 PM: ✔️ Successfully signed in to http://192.168.86.101:8080/admin!
1/22/2023, 2:57:31 PM: ➡️ Downloading backup from http://192.168.86.101:8080/admin...
1/22/2023, 2:57:31 PM: ✔️ Backup from http://192.168.86.101:8080/admin completed!
1/22/2023, 2:57:31 PM: ➡️ Signing in to http://192.168.86.102:8080/admin...
1/22/2023, 2:57:31 PM: ✔️ Successfully signed in to http://192.168.86.102:8080/admin!
1/22/2023, 2:57:31 PM: ➡️ Uploading backup to http://192.168.86.102:8080/admin...
1/22/2023, 2:57:42 PM: ⚠ Error: Failed to upload backup to "http://192.168.86.102:8080/admin".
1/22/2023, 2:57:42 PM: {"host":"http://192.168.86.102:8080","path":"/admin","status":200,"responseBody":"Processed adlist (42 entries)<br>\nProcessed adlist group assignments (42 entries)<br>\nProcessed blacklist (exact) (3 entries)<br>\nProcessed blacklist (regex) (1 entry)<br>\nProcessed client (0 entries)<br>\nProcessed client group assignments (0 entries)<br>\nProcessed local DNS records (2 entries)<br>\nProcessed static DHCP leases (16 entries)<br>\nProcessed black-/whitelist group assignments (279 entries)<br>\nProcessed group (1 entry)<br>\nProcessed whitelist (exact) (274 entries)<br>\nProcessed whitelist (regex) (1 entry)<br>\nOK<br>\n<span data-forcereload></span>"}
1/22/2023, 2:57:42 PM: ⚠ Failure: 0/1 hosts synced.
1/22/2023, 2:57:42 PM: Waiting 30 minutes...

**Comment by mattwebbio** [comment]
Hmmm, and this last run is using the prerelease?

**Comment by pmontgo33** [comment]
> Hmmm, and this last run is using the prerelease?

Yes it is

**Comment by kade-robertson** [comment]
Can confirm this is still happening on `1.5.2` and the `1.5.1-0` prerelease. Though, my DHCP leases _are_ still copied over correctly, so this seems like maybe just an error in logging / error handling?

**Comment by haydndup** [comment]
I'm running into the same issue. From the json output, it seems like the import is actually successful.

On container version `mattwebbio/orbital-sync:1`:
```
3/29/2023, 7:09:44 AM: ➡️ Signing in to http://192.168.86.201/admin...
3/29/2023, 7:09:44 AM: ✔️ Successfully signed in to http://192.168.86.201/admin!
3/29/2023, 7:09:44 AM: ➡️ Downloading backup from http://192.168.86.201/admin...
3/29/2023, 7:09:45 AM: ✔️ Backup from http://192.168.86.201/admin completed!
3/29/2023, 7:09:45 AM: ➡️ Signing in to http://192.168.86.202/admin...
3/29/2023, 7:09:45 AM: ✔️ Successfully signed in to http://192.168.86.202/admin!
3/29/2023, 7:09:45 AM: ➡️ Uploading backup to http://192.168.86.202/admin...
3/29/2023, 7:09:50 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.202/admin".
3/29/2023, 7:09:50 AM: ⚠ Failure: 0/1 hosts synced.
3/29/2023, 7:09:50 AM: {"host":"http://192.168.86.202","path":"/admin","status":200,"responseBody":"Start importing...<br>\nProcessed adlist (41 entries)<br>\nProcessed adlist group assignments (41 entries)<br>\nProcessed blacklist (exact) (27 entries)<br>\nProcessed blacklist (regex) (4 entries)<br>\nProcessed client (4 entries)<br>\nProcessed client group assignments (6 entries)<br>\nProcessed local DNS records (13 entries)<br>\nProcessed static DHCP leases (0 entries)<br>\nProcessed black-/whitelist group assignments (37 entries)<br>\nProcessed group (4 entries)<br>\nProcessed whitelist (exact) (6 entries)<br>\nProcessed whitelist (regex) (0 entries)<br>\nDone importing"}
3/29/2023, 7:09:50 AM: Waiting 30 minutes...
3/29/2023, 7:11:10 AM: ➡️ Signing in to http://192.168.86.201/admin...
3/29/2023, 7:11:11 AM: ✔️ Successfully signed in to http://192.168.86.201/admin!
3/29/2023, 7:11:11 AM: ➡️ Downloading backup from http://192.168.86.201/admin...
3/29/2023, 7:11:11 AM: ✔️ Backup from http://192.168.86.201/admin completed!
3/29/2023, 7:11:11 AM: ➡️ Signing in to http://192.168.86.202/admin...
3/29/2023, 7:11:11 AM: ✔️ Successfully signed in to http://192.168.86.202/admin!
3/29/2023, 7:11:11 AM: ➡️ Uploading backup to http://192.168.86.202/admin...
3/29/2023, 7:11:14 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.202/admin".
3/29/2023, 7:11:14 AM: ⚠ Failure: 0/1 hosts synced.
3/29/2023, 7:11:14 AM: {"host":"http://192.168.86.202","path":"/admin","status":200,"responseBody":"Start importing...<br>\nProcessed adlist (41 entries)<br>\nProcessed adlist group assignments (41 entries)<br>\nProcessed blacklist (exact) (27 entries)<br>\nProcessed blacklist (regex) (4 entries)<br>\nProcessed client (4 entries)<br>\nProcessed client group assignments (6 entries)<br>\nProcessed local DNS records (13 entries)<br>\nProcessed static DHCP leases (0 entries)<br>\nProcessed black-/whitelist group assignments (37 entries)<br>\nProcessed group (4 entries)<br>\nProcessed whitelist (exact) (6 entries)<br>\nProcessed whitelist (regex) (0 entries)<br>\nDone importing"}
```

On container `orbital-sync:1.5.1-0`:
```
3/29/2023, 7:17:37 AM: ➡️ Signing in to http://192.168.86.201/admin...
3/29/2023, 7:17:37 AM: ✔️ Successfully signed in to http://192.168.86.201/admin!
3/29/2023, 7:17:37 AM: ➡️ Downloading backup from http://192.168.86.201/admin...
3/29/2023, 7:17:38 AM: ✔️ Backup from http://192.168.86.201/admin completed!
3/29/2023, 7:17:38 AM: ➡️ Signing in to http://192.168.86.202/admin...
3/29/2023, 7:17:38 AM: ✔️ Successfully signed in to http://192.168.86.202/admin!
3/29/2023, 7:17:38 AM: ➡️ Uploading backup to http://192.168.86.202/admin...
3/29/2023, 7:17:45 AM: ⚠ Error: Failed to upload backup to "http://192.168.86.202/admin".
3/29/2023, 7:17:45 AM: {"host":"http://192.168.86.202","path":"/admin","status":200,"responseBody":"Start importing...<br>\nProcessed adlist (41 entries)<br>\nProcessed adlist group assignments (41 entries)<br>\nProcessed blacklist (exact) (27 entries)<br>\nProcessed blacklist (regex) (4 entries)<br>\nProcessed client (4 entries)<br>\nProcessed client group assignments (6 entries)<br>\nProcessed local DNS records (13 entries)<br>\nProcessed static DHCP leases (0 entries)<br>\nProcessed black-/whitelist group assignments (37 entries)<br>\nProcessed group (4 entries)<br>\nProcessed whitelist (exact) (6 entries)<br>\nProcessed whitelist (regex) (0 entries)<br>\nDone importing"}
3/29/2023, 7:17:45 AM: ⚠ Failure: 0/1 hosts synced.
3/29/2023, 7:17:45 AM: Waiting 30 minutes...
```

From my testing, the sync is actually working for domains, but partially for static leases - new static leases are copied over, but changes to existing leases are not (but not sure if that's a separate issue / expected behaviour).

**Comment by DuzAwe** [comment]
encountering the same.
`root-orbital-sync-1  | 4/24/2023, 6:07:31 PM: ➡️ Signing in to http://192.168.0.50/admin...
root-orbital-sync-1  | 4/24/2023, 6:07:32 PM: ✔️ Successfully signed in to http://192.168.0.50/admin!
root-orbital-sync-1  | 4/24/2023, 6:07:32 PM: ➡️ Downloading backup from http://192.168.0.50/admin...
root-orbital-sync-1  | 4/24/2023, 6:07:32 PM: ✔️ Backup from http://192.168.0.50/admin completed!
root-orbital-sync-1  | 4/24/2023, 6:07:32 PM: ➡️ Signing in to http://192.168.0.28/admin...
root-orbital-sync-1  | 4/24/2023, 6:07:32 PM: ✔️ Successfully signed in to http://192.168.0.28/admin!
root-orbital-sync-1  | 4/24/2023, 6:07:32 PM: ➡️ Uploading backup to http://192.168.0.28/admin...
root-orbital-sync-1  | 4/24/2023, 6:07:34 PM: ⚠ Error: Failed to upload backup to "http://192.168.0.28/admin".
root-orbital-sync-1  | 4/24/2023, 6:07:34 PM: {"host":"http://192.168.0.28","path":"/admin","status":200,"responseBody":"Start importing...<br>\nProcessed adlist (34 entries)<br>\nProcessed adlist group assignments (34 entries)<br>\nProcessed blacklist (exact) (0 entries)<br>\nProcessed blacklist (regex) (14 entries)<br>\nProcessed client (0 entries)<br>\nProcessed client group assignments (0 entries)<br>\nProcessed local DNS records (2 entries)<br>\nProcessed local CNAME records (0 entries)<br>\nProcessed black-/whitelist group assignments (221 entries)<br>\nProcessed group (1 entry)<br>\nProcessed whitelist (exact) (193 entries)<br>\nProcessed whitelist (regex) (14 entries)<br>\nDone importing"}
root-orbital-sync-1  | 4/24/2023, 6:07:34 PM: ⚠ Failure: 0/1 hosts synced.
root-orbital-sync-1  | 4/24/2023, 6:07:34 PM: Waiting 30 minutes...`

**Comment by mattwebbio** [comment]
@haydndup and @DuzAwe: I believe your issue is different from the above; yours are due to Orbital Sync expecting the success message to end with `OK` instead of `Done importing`. This _should_ have been fixed with the release of `1.5.2` and was previously reported and resolved in this issue: https://github.com/mattwebbio/orbital-sync/issues/162

I would make sure you've pulled the latest version of the container for tag `1` and try again!

**Comment by kade-robertson** [comment]
> 



> @haydndup and @DuzAwe: I believe your issue is different from the above; yours are due to Orbital Sync expecting the success message to end with `OK` instead of `Done importing`. This _should_ have been fixed with the release of `1.5.2` and was previously reported and resolved in this issue: #162
> 
> I would make sure you've pulled the latest version of the container for tag `1` and try again!

1.5.2 still has issues, it looks like if syncing DHCP leases is enabled, the response message no longer ends with `Done importing`.

```
4/25/2023, 5:39:33 PM: ⚠ Error: Failed to upload backup to "http://10.88.111.3:80/admin".
4/25/2023, 5:39:33 PM: {"host":"http://10.88.111.3:80","path":"/admin","status":200,"responseBody":"Start importing...<br>\nProcessed adlist (1 entry)<br>\nProcessed adlist group assignments (1 entry)<br>\nProcessed blacklist (exact) (0 entries)<br>\nProcessed blacklist (regex) (0 entries)<br>\nProcessed client (0 entries)<br>\nProcessed client group assignments (0 entries)<br>\nProcessed local DNS records (0 entries)<br>\nProcessed static DHCP leases (18 entries)<br>\nProcessed black-/whitelist group assignments (3 entries)<br>\nProcessed group (1 entry)<br>\nProcessed whitelist (exact) (3 entries)<br>\nProcessed whitelist (regex) (0 entries)<br>\nDone importing<br>\n<span data-forcereload></span>"}
```

If I disable the static DHCP lease syncing, it starts working again.

**Comment by DuzAwe** [comment]
For me, it looks like 1.5.2 has fixed the issue.

**Comment by haydndup** [comment]
@mattwebbio, can confirm that 1.5.2 fixes it for me too. Thanks!

**Comment by janusloo** [comment]
Hi I am facing this issue this morning. The sync always failed but it is synced. I am running the latest version and DHCP static leases are turned on. I have the following errors:

orbital-sync  | 1/27/2025, 8:15:01 AM: ✔️ Successfully signed in to http://dietpi.internal/admin!
orbital-sync  | 1/27/2025, 8:15:01 AM: ➡️ Downloading backup from http://dietpi.internal/admin...
orbital-sync  | 1/27/2025, 8:15:01 AM: ✔️ Backup from http://dietpi.internal/admin completed!
orbital-sync  | 1/27/2025, 8:15:01 AM: ➡️ Signing in to http://synonas.internal:1080/admin...
orbital-sync  | 1/27/2025, 8:15:01 AM: ✔️ Successfully signed in to http://synonas.internal:1080/admin!
orbital-sync  | 1/27/2025, 8:15:01 AM: ➡️ Uploading backup to http://synonas.internal:1080/admin...
orbital-sync  | 1/27/2025, 8:15:04 AM: ⚠ Error: Failed to upload backup to "http://synonas.internal:1080/admin".
orbital-sync  | 1/27/2025, 8:15:04 AM: ⚠ Failure: 0/1 hosts synced.
orbital-sync  | 1/27/2025, 8:15:04 AM: {"host":"http://synonas.internal:1080","path":"/admin","status":200,"responseBody":"Start importing...<br>\nProcessed adlist (1 entry)<br>\nProcessed adlist group assignments (1 entry)<br>\nProcessed blacklist (exact) (4 entries)<br>\nProcessed blacklist (regex) (14 entries)<br>\nProcessed client (0 entries)<br>\nProcessed client group assignments (0 entries)<br>\nProcessed local DNS records (9 entries)<br>\nProcessed static DHCP leases (8 entries)<br>\nProcessed black-/whitelist group assignments (28 entries)<br>\nProcessed group (1 entry)<br>\nProcessed whitelist (exact) (10 entries)<br>\nProcessed whitelist (regex) (0 entries)<br>\nDone importing<br>\n<span data-forcereload></span>"}


It was working fine before and now suddenly this happened. How can I troubleshoot this as the VERBOSE log does not give a lot of information. Thanks in advance!

**Comment by janusloo** [comment]
Hi, I did it from scratch again to test: wiped out the persistent storage for pihole docker and now it is working flawlessly. The sync completes successfully.

The static DHCP leases issue has also been resolved now. Thank you so much.
